file = open('name.txt', 'r', encoding='utf-8')
text = file.read()
print(text)
file.close()
file = open('middle name.txt', 'r',  encoding='utf-8')
text = file.read()
print(text)
file.close()
print('-здавствуйте, Полина Александровна!')