import time
mon = open('mon.txt', 'r', encoding='utf-8')
text = mon.read()
print(text)
mon.close()
time.sleep(1)
monot = open('mon.ot.txt', 'r', encoding='utf-8')
text = monot.read()
print(text)
monot.close()
time.sleep(1)
print(13659+55550, 'рублей, было до отпуска')
