p = open('q.txt', 'r',encoding='utf-8')
n = open('w.txt', 'r',encoding='utf-8')
g = open('e.txt', 'r',encoding='utf-8')
c=p.read()
a=n.read()
t=g.read()
print('предмет:',c)
print('предназначение:',a)
print('отличительные черты:',t)